s3:
    access_key_id: 'your_access_key_id__here'
    secret_access_key: 'your_secret_access_key_here'
    bucket_name: 'bucket_name_here'

image_settings:
    horizontal_res: 640
    vertical_res: 480
    file_name: 'test'
    file_extension: '.jpg'
    folder_name: 'images'
    awb_mode: 'auto'
    photo_interval: 60

debug: true
